[project]
name = "widsith"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jinja2>=3.1.6",
    "lxml>=5.4.0",
    "pandas>=2.2.3",
    "pyuca>=1.2",
]
